apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-emulator-deployment
  labels:
    app: pubsubthree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsubthree
  template:
    metadata:
      labels:
        app: pubsubthree
    spec:
      containers:
        - name: pubsubthree-emulator
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators          
---
apiVersion: v1
kind: Service
metadata:
  name: pubsubthree-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8085
      nodePort: 30001
  selector:
    app: pubsubthree
