apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-emulator-deployment
  labels:
    app: pubsubtwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsubtwo
  template:
    metadata:
      labels:
        app: pubsubtwo
    spec:
      containers:
        - name: pubsubtwo-emulator
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest          
---
apiVersion: v1
kind: Service
metadata:
  name: pubsubtwo-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8085
      nodePort: 30001
  selector:
    app: pubsubtwo
