name: List Secrets and Variables

on:
  workflow_dispatch:

jobs:
  list-secrets-variables:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - name: Get GitHub environment variables and secrets
        shell: pwsh
        run: |
          echo  "ssss ${{ vars.RAJIB_VARIABLE2}}"
          Write-Output "Serect  RAJIB_VARIABLE2 ${{ vars.RAJIB_VARIABLE2 }} "
          Write-Output "Serect  RAJIBSECRET2 ${{ secrets.RAJIBSECRET1}} "
            
         
