name: List Secrets and Variables

on:
  workflow_dispatch:

jobs:
  list-secrets-variables:
    runs-on: windows-latest

    steps:
      - name: Get GitHub environment variables and secrets
        id: get_env_vars
        run: |
          echo  "ssss ${{ vars.RAJIB_VARIABLE2}}"
          Write-Output "Serect  RAJIB_VARIABLE2 ${{ vars.RAJIB_VARIABLE2 }} "
          Write-Output "Serect  RAJIBSECRET2 ${{ secrets.RAJIBSECRET1}} "
            
         
