name: List Secrets and Variables

on:
  workflow_dispatch:

jobs:
  list-secrets-variables:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub environment variables and secrets
        id: get_env_vars
        run: |
          $env_variables_url = "https://api.github.com/repos/${{ $env:GITHUB_REPOSITORY }}/environments/DEV/secrets"
          $secrets_url = "https://api.github.com/repos/${{ $env:GITHUB_REPOSITORY }}/actions/secrets"

          $env_variables_response = Invoke-RestMethod -Uri $env_variables_url -Headers @{Authorization = "Bearer {{ $env:GITHUB_TOKEN"}} } 
          $secrets_response = Invoke-RestMethod -Uri $secrets_url -Headers @{Authorization = "Bearer {{ $env:GITHUB_TOKEN" }} }

          $env_variables_response.data | ForEach-Object {
              Write-Output "Environment Variable: $($_.name), Value: $($_.value)"
          }

          $secrets_response.secrets | ForEach-Object {
              Write-Output "Secret: $($_.name)"
          }
