name: List Secrets and Variables

on:
  workflow_dispatch:

jobs:
  list-secrets-variables:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub environment variables and secrets
        id: get_env_vars
        run: |
          Write-Output "Serect  RAJIBSECRET1 ${{ secrets.RAJIBSECRET1}} "
          Write-Output "Serect  RAJIBSECRET2 ${{ secrets.RAJIBSECRET1}} "
            
         
