name: List Secrets and Variables

on:
  workflow_dispatch:

jobs:
  list-secrets-variables:
    runs-on: windows-latest

    steps:
      - name: Get GitHub environment variables and secrets
        id: get_env_vars
        run: |
          echo  ${{ secrets.RAJIBSECRET1}}
          Write-Output "Serect  RAJIBSECRET1 ${{ secrets.RAJIBSECRET1}} "
          Write-Output "Serect  RAJIBSECRET2 ${{ secrets.RAJIBSECRET1}} "
            
         
